server:
  port: 5000
  error:
    include-message: always

spring:
  jackson:
    # Meaningful for the auto-mapping naming java<->JSON (to avoid extra annotations in the code)
    property-naming-strategy: SNAKE_CASE

springdoc:
  api-docs:
    # If enables is set to true then the links to API documentation will be visible on happy page
    enabled: true
    packages-to-scan: com.mau.hireme.mvc.rest
  swagger-ui:
    # Next one is meaningful only if api-docs.enabled=true
    enabled: true

hireme:
  integration:
    pokeapi:
      base-uri: https://pokeapi.co/api
    shakespearetran-api:
      base-uri: https://api.funtranslations.com/translate
      # Enabled was introduced to avoid consuming all the daily free calls, if false the call to the Shakespeare
      # translation API won't be made and NOT translated text, with a warning, will be returned
      enabled: true

logging:
  level:
    root: INFO
