server:
  port: 5000
  error:
    include-message: always

spring:
  jackson:
    property-naming-strategy: SNAKE_CASE

hireme:
  integration:
    pokeapi:
      base-uri: https://pokeapi.co/api
    shakespearetran-api:
      base-uri: https://api.funtranslations.com/translate
      # Enabled was introduced to avoid consuming all the daily free calls
      enabled: true
